safe-reboot: save backup in a .tgz file instead of a mirrored tree

diff --git a/packages/safe-reboot/files/usr/sbin/safe-reboot b/packages/safe-reboot/files/usr/sbin/safe-reboot
--- a/packages/safe-reboot/files/usr/sbin/safe-reboot
+++ b/packages/safe-reboot/files/usr/sbin/safe-reboot
@@ -29,8 +29,8 @@
 ###    restarting the network), and if something goes wrong so you can't
 ###    login, just wait for the fallback timeout.
 ###  Even more, you can make actual changes to /etc config and reboot. If it
-###    comes up right, you can login and simply delete the backup directory
-###    /etc.last-good . But if something went wrong with the new /etc, 
+###    comes up right, you can login and simply delete the backup
+###    /etc.last-good.tgz . But if something went wrong with the new /etc, 
 ###    again just wait for the revert timeout.
 ###  
 ###  -w, --wait, --in TIME
@@ -38,14 +38,14 @@
 ###          Default: 5min
 ###  -f, --fallback-after TIME
 ###        After boot, wait for TIME before reverting /overlay/etc from 
-###        backup found in /overlay/etc.last-good
+###        backup found in /overlay/etc.last-good.tgz
 ###          Default: 10min
 ###  now
 ###        Do not make /overlay/etc backup; instead check that there's
-###        one already in place (/overlay/etc.last-good), then reboot
+###        one already in place (/overlay/etc.last-good.tgz), then reboot
 ###        and wait for fallback timeout.
 ###  cancel
-###        Remove /overlay/etc.last-good/
+###        Remove /overlay/etc.last-good.tgz
 ###        (useful after a successful reboot)
 ### 
 ###    TIME examples: 1hour 60min 60m 3600sec 3600
@@ -57,7 +57,7 @@
 PIDFILE="/tmp/run/safe-reboot.pid"
 fallback_timeout=600
 grace_period=300
-dir_etc_lastgood="/overlay/etc.last-good/"
+file_etc_lastgood="/overlay/etc.last-good.tgz"
 dir_etc="/overlay/etc/"
 safe_fallback_script="/overlay/etc/uci-defaults/safe-fallback"
 
@@ -77,12 +77,12 @@ timetoseconds() { # valid and equivalent input examples: 3600 3600s 3600sec 60mi
         echo $seconds
 }
 backup_etc_exists () {
-  [ -d "$dir_etc_lastgood" ]
+  [ -s "$file_etc_lastgood" ]
 }
 
 backup_etc () {
-  rm -rf "$dir_etc_lastgood"
-  cp -a "$dir_etc" "$dir_etc_lastgood"
+  rm -f "$file_etc_lastgood"
+  tar -czf "$file_etc_lastgood" -C "$dir_etc" .
 }
 
 write_safe_fallback_script () {
@@ -92,11 +92,12 @@ write_safe_fallback_script () {
   chmod +x "$safe_fallback_script"
   cat <<EOF > "$safe_fallback_script"
 #!/bin/sh
-( [ -d "$dir_etc_lastgood" ] \
+( [ -s "$file_etc_lastgood" ] \
   && sleep $fallback_timeout & trap 'kill $! ; exit' TERM ; wait \
-  && if [ -d $dir_etc_lastgood ] ; then
-      rm -rf $dir_etc
-      mv -f $dir_etc_lastgood $dir_etc
+  && if [ -s $file_etc_lastgood ] ; then
+      rm -rf $dir_etc ; mkdir -p $dir_etc
+      tar -xzf $file_etc_lastgood -C $dir_etc
+      rm -f $file_etc_lastgood
       reboot 
   fi ) &
 echo $! > "$PIDFILE"
@@ -110,9 +111,9 @@ reboot_after_grace_period () {
 }
 
 action_cancel () {
-  rm -rf "$dir_etc_lastgood"
+  rm -f "$file_etc_lastgood"
   rm -f "$safe_fallback_script"
-  echo -n "Removed $dir_etc_lastgood, "
+  echo -n "Removed $file_etc_lastgood, "
   if [ -s "$PIDFILE" ] ; then
     kill "$(cat "$PIDFILE")"
     rm -f "$PIDFILE"
@@ -139,9 +140,9 @@ while [ -n "$1" ]; do
 done
 
 if [ "$grace_period" -eq 0 ] ; then
-  backup_etc_exists || { echo "STOP! Directory $dir_etc_lastgood not found! Refusing to continue." ; exit 2 ; }
+  backup_etc_exists || { echo "STOP! Backup file $file_etc_lastgood not found! Refusing to continue." ; exit 2 ; }
 else
-  backup_etc_exists && { echo "STOP! Directory $dir_etc_lastgood exists! You probably want to \`$0 now\`" ; exit 4 ; }
+  backup_etc_exists && { echo "STOP! Backup file $file_etc_lastgood exists! You probably want to \`$0 now\`" ; exit 4 ; }
   backup_etc || { echo "STOP! Backup failed. Refusing to continue." ; exit 8 ; }
 fi
 
