shared-state-async: expose publish all

diff --git a/packages/shared-state-async/files/usr/libexec/rpcd/shared-state-async b/packages/shared-state-async/files/usr/libexec/rpcd/shared-state-async
--- a/packages/shared-state-async/files/usr/libexec/rpcd/shared-state-async
+++ b/packages/shared-state-async/files/usr/libexec/rpcd/shared-state-async
@@ -11,7 +11,7 @@ sinc_args=""
  
 case "$1" in 
     list) 
-        echo '{ "sync": { "data_type": "str", "peers_ip": "str" }, "get": { "data_type": "str" },  "publish": { "data_type": "str" } }'
+        echo '{ "sync": { "data_type": "str", "peers_ip": "str" }, "get": { "data_type": "str" },  "publish": { "data_type": "str" }, "publish_all": { } }'
     ;; 
     call)
         # source jshn shell library
@@ -36,6 +36,10 @@ case "$1" in
             publish) 
                 /usr/share/shared-state/publishers/shared-state-publish_$data_type > /dev/null 2>&1
                 echo {\"data\": {} , \"error\": $? } 
+            ;;
+            publish_all)
+                shared-state-async-publish-all > /dev/null 2>&1
+                echo {\"data\": {} , \"error\": $? }
             ;;
             *)
                  echo '{\"data\" {} ,\"error\" = "Method not found"}' 
