RegHack install module only if binary patching succed on all of the + report status

diff --git a/packages/reghack/Makefile b/packages/reghack/Makefile
--- a/packages/reghack/Makefile
+++ b/packages/reghack/Makefile
@@ -45,14 +45,36 @@ endef
 
 define Package/$(PKG_NAME)/postinst
 #!/bin/sh
-for module in ath cfg80211 ; do
-	cp "$$IPKG_INSTROOT"/lib/modules/*/$${module}.ko /tmp/
-	if reghack /tmp/$${module}.ko ; then
-		mv -f /tmp/$${module}.ko "$$IPKG_INSTROOT"/lib/modules/*/
-	else
-		rm -f /tmp/$${module}.ko
-	fi
+
+workDir="/tmp/reghack-apply/"
+modules="ath cfg80211"
+modulesDir="$$IPKG_INSTROOT/lib/modules/"
+etcDir="$$IPKG_INSTROOT/etc/reghack/"
+statusFile="$${etcDir}/status"
+logFile="$${etcDir}/log"
+hackOk=0
+
+mkdir -p $${workDir}
+mkdir -p $${etcDir}
+
+for module in $${modules} ; do
+	cp $${modulesDir}/*/$${module}.ko $${workDir}
+	reghack $${workDir}/$${module}.ko >> $${logFile} 2>&1
+	hackOk=$$((hackOk+$$?))
 done
+
+if [ "$${hackOk}" -eq 0 ]
+	then
+		mv -f $${workDir}/*.ko "$${modulesDir}"/*/
+		echo "RegHack succeded on $${modules}" > $${statusFile}
+	else
+		echo "RegHack failed" > $${statusFile}
+fi
+
+rm -rf $${workDir}
+
 exit 0
+
 endef
+
 $(eval $(call BuildPackage,$(PKG_NAME)))
