qemu: allow building a network with multiple nodes

diff --git a/tools/qemu_dev_start b/tools/qemu_dev_start
--- a/tools/qemu_dev_start
+++ b/tools/qemu_dev_start
@@ -16,21 +16,26 @@
 #    along with this program.  If not, see <https://www.gnu.org/licenses/>.
 #
 # ARG_OPTIONAL_SINGLE([libremesh-workdir],[],[Optional path to a libremesh working directory to include it as a layer over the rootfs.])
+# ARG_OPTIONAL_SINGLE([node-number],[],[Optional node number from 0 to 9. Use this when running multiple qemu nodes.],[0])
 # ARG_OPTIONAL_BOOLEAN([enable-wan],[],[Enable wan (needs dnsmasq installed)],[])
 # ARG_OPTIONAL_BOOLEAN([verbose],[],[Turn on verbose mode],[])
 # ARG_POSITIONAL_SINGLE([rootfs],[Path to a x86-64-generic-rootfs.tar.gz],[])
 # ARG_POSITIONAL_SINGLE([ramfs],[Path to a x86-64-ramfs.bzImage],[])
 # ARG_HELP([Helper to run libremesh in a qemu x86_64 for development purposes])
 # ARGBASH_GO()
-### START OF CODE GENERATED BY Argbash v2.8.1 one line above, https://argbash.io/generate ###
+# needed because of Argbash --> m4_ignore([
+### START OF CODE GENERATED BY Argbash v2.9.0 one line above ###
+# Argbash is a bash code generator used to get arguments parsing right.
+# Argbash is FREE SOFTWARE, see https://argbash.io for more info
+# Generated online by https://argbash.io/generate
+
 
 die()
 {
-	local _ret=$2
-	test -n "$_ret" || _ret=1
-	test "$_PRINT_HELP" = yes && print_help >&2
+	local _ret="${2:-1}"
+	test "${_PRINT_HELP:-no}" = yes && print_help >&2
 	echo "$1" >&2
-	exit ${_ret}
+	exit "${_ret}"
 }
 
 
@@ -45,6 +50,7 @@ begins_with_short_option()
 _positionals=()
 # THE DEFAULTS INITIALIZATION - OPTIONALS
 _arg_libremesh_workdir=
+_arg_node_number="0"
 _arg_enable_wan="off"
 _arg_verbose="off"
 
@@ -52,10 +58,11 @@ _arg_verbose="off"
 print_help()
 {
 	printf '%s\n' "Helper to run libremesh in a qemu x86_64 for development purposes"
-	printf 'Usage: %s [--libremesh-workdir <arg>] [--(no-)enable-wan] [--(no-)verbose] [-h|--help] <rootfs> <ramfs>\n' "$0"
+	printf 'Usage: %s [--libremesh-workdir <arg>] [--node-number <arg>] [--(no-)enable-wan] [--(no-)verbose] [-h|--help] <rootfs> <ramfs>\n' "$0"
 	printf '\t%s\n' "<rootfs>: Path to a x86-64-generic-rootfs.tar.gz"
 	printf '\t%s\n' "<ramfs>: Path to a x86-64-ramfs.bzImage"
 	printf '\t%s\n' "--libremesh-workdir: Optional path to a libremesh working directory to include it as a layer over the rootfs. (no default)"
+	printf '\t%s\n' "--node-number: Optional node number. Use this when running multiple qemu nodes. (default: '0')"
 	printf '\t%s\n' "--enable-wan, --no-enable-wan: Enable wan (needs dnsmasq installed) (off by default)"
 	printf '\t%s\n' "--verbose, --no-verbose: Turn on verbose mode (off by default)"
 	printf '\t%s\n' "-h, --help: Prints help"
@@ -76,6 +83,14 @@ parse_commandline()
 				;;
 			--libremesh-workdir=*)
 				_arg_libremesh_workdir="${_key##--libremesh-workdir=}"
+				;;
+			--node-number)
+				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+				_arg_node_number="$2"
+				shift
+				;;
+			--node-number=*)
+				_arg_node_number="${_key##--node-number=}"
 				;;
 			--no-enable-wan|--enable-wan)
 				_arg_enable_wan="on"
@@ -130,7 +145,6 @@ parse_commandline "$@"
 handle_passed_args_count
 assign_positional_args 1 "${_positionals[@]}"
 
-
 #####################
 
 
@@ -138,25 +152,41 @@ if [[ "$_arg_verbose" == "on" ]]; then
     set -x
 fi
 
-# LAN ifc. We may use a DHCP client, but we are forcing a fixed ip
-ip tuntap add name lime_tap0 mode tap
-ip addr add 10.13.0.99/24 dev lime_tap0
-ip link set lime_tap0 up
+BRIDGE_IFC="lime_br0"
+NODE_NUMBER="${_arg_node_number}"
+LAN_MAC="52:00:00:ab:cd:0${NODE_NUMBER}"
+WAN_MAC="52:00:00:ab:cd:a${NODE_NUMBER}"
+LAN_IFC="lime_tap${NODE_NUMBER}0"
+WAN_IFC="lime_tap${NODE_NUMBER}1"
+OWN_LAN_IP="10.13.0.2/16"
+
+
+if [ ! -e "/sys/class/net/$BRIDGE_IFC" ]; then
+    ip link add name "$BRIDGE_IFC" type bridge
+    ip link set "$BRIDGE_IFC" up
+    ip addr add "$OWN_LAN_IP" dev "$BRIDGE_IFC"
+fi
+
+# No IP for the tap LAN ifc
+ip tuntap add name "$LAN_IFC" mode tap
+ip link set "$LAN_IFC" up
+ip link set "$LAN_IFC" master "$BRIDGE_IFC"
+
 
 if [[ "$_arg_enable_wan" == "on" ]]; then
     # WAN ifc
-    ip tuntap add name lime_tap1 mode tap
-    ip addr add 172.99.0.1/24 dev lime_tap1
-    ip link set lime_tap1 up
+    ip tuntap add name "$WAN_IFC" mode tap
+    ip addr add 172.99.0.1/24 dev "$WAN_IFC"
+    ip link set "$WAN_IFC" up
 
     # DHCP server for WAN ifc
-    dnsmasq -F 172.99.0.100,172.99.0.100 --dhcp-option=3,172.99.0.1 -i lime_tap1 --dhcp-authoritative --log-dhcp
+    dnsmasq -F 172.99.0.100,172.99.0.100 --dhcp-option=3,172.99.0.1 -i "$WAN_IFC" --dhcp-authoritative --log-dhcp
 
     # enable forwarding and NAT
     echo 1 > /proc/sys/net/ipv4/ip_forward
     iptables -t nat -A POSTROUTING -o wlan0 -j MASQUERADE
     iptables -A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-    iptables -A FORWARD -i  lime_tap1  -o wlan0 -j ACCEPT
+    iptables -A FORWARD -i  "$WAN_IFC"  -o wlan0 -j ACCEPT
 fi
 
 # Convert the rootfs.tar.gz into a cpio file
@@ -180,7 +210,7 @@ cd /tmp/lime_rootfs
 find . -depth | cpio --quiet -o -H newc  > /tmp/lime_rootfs.cpio
 cd - > /dev/null
 
-MONITOR_PORT="45454"
+MONITOR_PORT="4545${NODE_NUMBER}"
 
 qemu-system-x86_64 \
 -m 128 \
@@ -194,18 +224,18 @@ qemu-system-x86_64 \
 -initrd /tmp/lime_rootfs.cpio \
 -serial mon:stdio \
 -monitor "telnet::${MONITOR_PORT},server,nowait" \
--netdev tap,id=hostnet0,ifname=lime_tap0,script=no,downscript=no \
--device e1000,netdev=hostnet0,id=net0,mac=52:00:00:ab:cd:00,bus=pci.0,addr=0x3 \
--netdev tap,id=hostnet1,ifname=lime_tap1,script=no,downscript=no \
--device e1000,netdev=hostnet1,id=net1,mac=52:00:00:ab:cd:01,bus=pci.0,addr=0x4
+-netdev tap,id=hostnet0,ifname="${LAN_IFC}",script=no,downscript=no \
+-device e1000,netdev=hostnet0,id=net0,mac="${LAN_MAC}",bus=pci.0,addr=0x3 \
+-netdev tap,id=hostnet1,ifname="${WAN_IFC}",script=no,downscript=no \
+-device e1000,netdev=hostnet1,id=net1,mac="${WAN_MAC}",bus=pci.0,addr=0x4
 
 
 # cleanup
-ip tuntap del name lime_tap0 mode tap
+ip tuntap del name ${LAN_IFC} mode tap
 
 if [[ "$_arg_enable-wan" == "on" ]]; then
 
-    ip tuntap del name lime_tap1 mode tap
+    ip tuntap del name "${WAN_IFC}" mode tap
 
     # End dnsmasaq
     kill -TERM `cat /var/run/dnsmasq.pid`
