ci: add multi branch build; add initial support for apk
lime-system: add apk option in 92_add-lime-repos

ci: update feeds scheme to build C++ packages for 3 lastest openwrt branches
      the new scheme make these packages available at
      https://github.com/libremesh/lime-feed
      referenced by apk in /etc/apk/repositories as
      libremesh_arch_packages https://feed.libremesh.org/arch_packages/master/openwrt-main/x86_64/packages.adb

ci: do not sign packages in main openwrt branch
      to install packages use "apk add --allow-untrusted lime-docs"

diff --git a/.github/workflows/multi-arch-build.yml b/.github/workflows/multi-arch-build.yml
--- a/.github/workflows/multi-arch-build.yml
+++ b/.github/workflows/multi-arch-build.yml
@@ -9,79 +9,134 @@ on:
       - v*
       - '!v2020*'
     paths:
+      - ".github/workflows/multi-arch-build.yml"
       - 'packages/shared-state-async/**'
 
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
 
+# Build packages using the openwrt sdk
+# for each architecture supported
+# in openwrt branches 'main', 'stable', 'old-stable'
+env:
+# NOTE:
+# workaround: build a package that selects '+shared-state-async'
+# as 'make package/shared-state-async/check' fails with 'Package HASH check failed'
+  PACKAGES: "shared-state-bat_hosts"
+
 jobs:
-  build:
-    name: build ${{ matrix.arch }} ${{ github.ref }}
+  generate_matrix:
+    name: 'Generate matrix'
     runs-on: ubuntu-latest
+    outputs:
+      matrix_builds: ${{ steps.define_matrix.outputs.matrix_builds }}
+      dest_dir: ${{ steps.set_package_destination.outputs.DEST_DIR }}
+    steps:
+      - name: Set package destination
+        id: set_package_destination
+        run: |
+          export TAG=$(echo "${{ github.ref }}" | cut -d '/' -f 3- | perl -pe 's/v([0-9])/$1/')
+          echo "$TAG"
+          echo "DEST_DIR=$TAG" >> $GITHUB_OUTPUT
+
+      - name: Define matrix of branches and archs
+        id: define_matrix
+        run: |
+          JSON='['
+          FIRST_BUILD=1
+          versions=$(curl https://downloads.openwrt.org/.versions.json)
+          stable=$(echo $versions | jq | grep \"stable_ | sed 's|.*\"stable_version\": \"\(.*\)\",|\1|')
+          oldstable=$(echo $versions | jq | grep oldstable_ | sed 's|.*\"oldstable_version\": \"\(.*\)\",|\1|')
+
+          for version in "main" "${stable:0:5}" "${oldstable:0:5}"; do
+
+            VERSION=$([ "$version" == "main" ] \
+              && echo "main" || echo "openwrt-$version")
+            echo $VERSION
+
+            VERSION_PATH=$([ "$version" == "main" ] \
+              && echo "snapshots/packages" || echo "releases/packages-$version")
+            echo $VERSION_PATH
+
+            OPENWRT_BRANCH_PATH=$([ "$version" == "main" ] \
+              && echo "openwrt-main" || echo "openwrt-$version")
+            echo $OPENWRT_BRANCH_PATH
+
+            wget -r -nH --no-parent --level 1 --accept html -P. \
+              --directory-prefix=. https://downloads.openwrt.org/$VERSION_PATH/  
+
+            for arch in $(ls ./$VERSION_PATH/ | grep -v html); do
+              [[ $FIRST_BUILD -ne 1 ]] && JSON="$JSON"','
+              FIRST_BUILD=0
+
+              JSON="$JSON"'{"version": "'"$VERSION"'" ,"arch": "'"$arch"'", "openwrt_branch_path": "'"$OPENWRT_BRANCH_PATH"'" }'
+              echo $JSON
+            done
+          done
+
+          matrix_include='{"include": '"$JSON"']}'
+          echo "matrix_builds=${matrix_include}" >> "$GITHUB_OUTPUT"
+          
+  build:
+    name: build ${{ matrix.arch }}-${{ matrix.version }}
+    runs-on: ubuntu-latest
+    needs: generate_matrix
     strategy:
       fail-fast: false
-      max-parallel: 1
-      matrix:
-        arch:
-          - aarch64_cortex-a53
-          - aarch64_cortex-a72
-          - aarch64_generic
-          - arm_arm1176jzf-s_vfp
-          - arm_arm926ej-s
-          - arm_cortex-a15_neon-vfpv4
-          - arm_cortex-a5_vfpv4
-          - arm_cortex-a7
-          - arm_cortex-a7_neon-vfpv4
-          - arm_cortex-a7_vfpv4
-          - arm_cortex-a8_vfpv3
-          - arm_cortex-a9
-          - arm_cortex-a9_neon
-          - arm_cortex-a9_vfpv3-d16
-          - arm_fa526
-          - arm_mpcore
-          - arm_xscale
-          - i386_pentium-mmx
-          - i386_pentium4
-          - mips64_octeonplus
-          - mips_24kc
-          - mips_4kec
-          - mips_mips32
-          - mipsel_24kc
-          - mipsel_24kc_24kf
-          - mipsel_74kc
-          - mipsel_mips32
-          - powerpc_464fp
-          - powerpc_8548
-          - riscv64_riscv64
-          - x86_64
-
+      max-parallel: 10
+      matrix: ${{ fromJson(needs.generate_matrix.outputs.matrix_builds) }}
+      # matrix:
+      #   include:
+      #     - { version: main, arch: x86_64, openwrt_branch_path: 'openwrt-main'}
+      #     - { version: main, arch: mips_24kc, openwrt_branch_path: 'openwrt-main'}
     steps:
       - uses: actions/checkout@v4
 
-      - name: Build packages ${{ matrix.arch }}
+      - name: Build packages ${{ matrix.arch }}-${{ matrix.version }}
         uses: openwrt/gh-action-sdk@v7
         env:
-          ARCH: "${{ matrix.arch }}-openwrt-23.05"
+          ARCH: "${{ matrix.arch }}-${{ matrix.version }}"
           FEEDNAME: "libremesh"
           IGNORE_ERRORS: "n m y"
-          KEY_BUILD: "${{ secrets.KEY_BUILD }}"
-          PACKAGES: "shared-state-bat_hosts"
+          KEY_BUILD: "${{ matrix.version != 'main' && secrets.KEY_BUILD || '' }}"
+          PACKAGES: "${{ env.PACKAGES }}"
           INDEX: 1
           NO_DEFAULT_FEEDS: 1
           NO_REFRESH_CHECK: 1
           NO_SHFMT_CHECK: 1
 
-      - name: Set package destination
-        run: |
-          export TAG=$(echo "${{ github.ref }}" | cut -d '/' -f 3- | perl -pe 's/v([0-9])/$1/')
-          echo "$TAG"
-          echo "DEST_DIR=$TAG" >> $GITHUB_ENV
+      - name: upload artifact
+        if: ${{ always() }}
+        uses: actions/upload-artifact@v4
+        with:
+          name: ${{ matrix.arch }}-${{ matrix.version }}
+          path: bin/packages/${{ matrix.arch }}/libremesh/
+
+  publish:
+    name: publish ${{ github.ref }}
+    runs-on: ubuntu-latest
+    if: ${{ always() }}
+    needs: [generate_matrix, build]
+    strategy:
+      fail-fast: false
+      max-parallel: 1
+      matrix: ${{ fromJson(needs.generate_matrix.outputs.matrix_builds) }}
+      # matrix:
+      #   include:
+      #     - { version: main, arch: x86_64, openwrt_branch_path: 'openwrt-main'}
+      #     - { version: main, arch: mips_24kc, openwrt_branch_path: 'openwrt-main'}
+    steps:
+      - uses: actions/checkout@v4
+
+      - uses: actions/download-artifact@v4
+        with:
+          name: "${{ matrix.arch }}-${{ matrix.version }}"
+          path: artifacts
 
       - name: Upload packages to GitHub Pages
-        uses: peaceiris/actions-gh-pages@v3
+        uses: peaceiris/actions-gh-pages@v4
         with:
           deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
           external_repository: libremesh/lime-feed
-          publish_dir: bin/packages/${{ matrix.arch }}/libremesh/
-          destination_dir: arch_packages/${{ env.DEST_DIR }}/${{ matrix.arch }}
-
+          publish_dir: ./artifacts/
+          destination_dir: arch_packages/${{ needs.generate_matrix.outputs.dest_dir }}/${{ matrix.openwrt_branch_path }}/${{ matrix.arch }}/
diff --git a/packages/lime-system/files/etc/uci-defaults/92_add-lime-repos b/packages/lime-system/files/etc/uci-defaults/92_add-lime-repos
--- a/packages/lime-system/files/etc/uci-defaults/92_add-lime-repos
+++ b/packages/lime-system/files/etc/uci-defaults/92_add-lime-repos
@@ -5,31 +5,65 @@
 	exit 0
 }
 
-feeds_file="/etc/opkg/limefeeds.conf"
+[ -f /etc/apk/repositories.d/distfeeds.list ] && {
+	repo='apk'
+	feeds_file='/etc/apk/repositories.d/limefeeds.list'
+	dist_feeds_file='/etc/apk/repositories.d/distfeeds.list'
+	main_feed_path='apk/'
+	arch="$(cat /etc/apk/arch)"
+} || ([ -f /etc/opkg/distfeed.conf ] && {
+	repo='opkg'
+	feeds_file='/etc/opkg/limefeeds.conf'
+	dist_feeds_file='/etc/opkg/distfeeds.conf'
+	main_feed_path=''
+	arch="$(grep OPENWRT_ARCH /etc/os-release | sed 's/OPENWRT_ARCH=\"\(.*\)\"/\1/')"
+	key_name="a71b3c8285abd28b"
+	key_content="RWSnGzyChavSiyQ+vLk3x7F0NqcLa4kKyXCdriThMhO78ldHgxGljM/8"
+})
+
+[ -z "$repo" ] && {
+	echo "Package manager not found - skipping"
+	exit 0
+}
 
 [ -f "$feeds_file" ] && {
-  echo "LibreMesh opkg feeds already defined - skipping"
-  exit 0
+  echo "LibreMesh $repo feeds already defined - skipping"
+  exit 0;
 }
 
-arch_packages="$(grep OPENWRT_ARCH /etc/os-release | sed 's/OPENWRT_ARCH=\"\(.*\)\"/\1/')"
+openwrt_branch_ref="$(grep -m 1 "openwrt.org/" $dist_feeds_file | sed 's|.*openwrt.org/\(.*\)|\1|' )"
+
+if [ '' != "$openwrt_branch_ref" ]; then
+$(echo $openwrt_branch_ref | grep -q 'snapshots') && {
+	openwrt_branch='openwrt-main'
+} || ($(echo $openwrt_branch_ref | grep -q 'releases') && {
+	branch_n="$(echo $openwrt_branch_ref | sed 's/releases\///')"
+	openwrt_branch="openwrt-${branch_n:0:5}"
+})
+else
+	echo "String not found 'openwrt.org' in default ${repo} feeds, cannot determine openwrt branch"
+fi
 
 [ "$LIME_CODENAME" == "development" ] && {
-	packages_url="http://feed.libremesh.org/master";
-	arch_packages_url="http://feed.libremesh.org/arch_packages/master/$arch_packages";
+	packages_url="http://feed.libremesh.org/${main_feed_path}master";
+	arch_packages_url="http://feed.libremesh.org/arch_packages/master/$openwrt_branch/$arch";
 } || {
-	packages_url="http://feed.libremesh.org/$LIME_RELEASE"
-	arch_packages_url="http://feed.libremesh.org/arch_packages/$LIME_RELEASE/$arch_packages";
+	packages_url="http://feed.libremesh.org/${main_feed_path}$LIME_RELEASE"
+	arch_packages_url="http://feed.libremesh.org/arch_packages/$LIME_RELEASE/$openwrt_branch/$arch";
 }
 
-profiles_url="http://feed.libremesh.org/profiles"
+profiles_url="http://feed.libremesh.org/${main_feed_path}profiles"
 
-key_name="a71b3c8285abd28b"
-key_content="RWSnGzyChavSiyQ+vLk3x7F0NqcLa4kKyXCdriThMhO78ldHgxGljM/8"
-
-echo "Configuring official LibreMesh opkg feeds"
+echo "Configuring official LibreMesh $repo feeds"
+[ $repo == 'apk' ] && {
+echo "$packages_url/packages.adb" > "$feeds_file"
+echo "${arch_packages_url}/packages.adb" >> "$feeds_file"
+echo "$profiles_url/packages.adb" >> "$feeds_file"
+} || ( 
+[ $repo == 'opkg' ] && {
 echo "src/gz libremesh $packages_url" > "$feeds_file"
 echo "src/gz libremesh_arch_packages $arch_packages_url" >> "$feeds_file"
 echo "src/gz profiles $profiles_url" >> "$feeds_file"
 echo "untrusted comment: signed by libremesh.org key $key_name" > "/etc/opkg/keys/$key_name"
 echo "$key_content" >> "/etc/opkg/keys/$key_name"
+})
